# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud_medi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crud_medi(object):
    def setupUi(self, crud_medi):
        crud_medi.setObjectName("crud_medi")
        crud_medi.resize(1080, 700)
        crud_medi.setMinimumSize(QtCore.QSize(1080, 700))
        crud_medi.setMaximumSize(QtCore.QSize(1080, 700))
        self.centralwidget = QtWidgets.QWidget(crud_medi)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_crud_medi = QtWidgets.QLabel(self.centralwidget)
        self.titulo_crud_medi.setGeometry(QtCore.QRect(0, 50, 1081, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG Inline")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_crud_medi.setFont(font)
        self.titulo_crud_medi.setStyleSheet("font-family: Decotura ICG Inline;\n"
"font-size: 50pt;")
        self.titulo_crud_medi.setTextFormat(QtCore.Qt.PlainText)
        self.titulo_crud_medi.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_crud_medi.setObjectName("titulo_crud_medi")
        self.tabla_medi = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_medi.setGeometry(QtCore.QRect(50, 140, 981, 192))
        self.tabla_medi.setObjectName("tabla_medi")
        self.tabla_medi.setColumnCount(0)
        self.tabla_medi.setRowCount(0)
        self.introducir_tel3 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_tel3.setGeometry(QtCore.QRect(60, 570, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_tel3.setFont(font)
        self.introducir_tel3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_tel3.setObjectName("introducir_tel3")
        self.introducir_ap3 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_ap3.setGeometry(QtCore.QRect(390, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_ap3.setFont(font)
        self.introducir_ap3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_ap3.setObjectName("introducir_ap3")
        self.boton_salir6 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir6.setGeometry(QtCore.QRect(920, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(30)
        self.boton_salir6.setFont(font)
        self.boton_salir6.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 30pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_salir6.setObjectName("boton_salir6")
        self.boton_actualizar3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_actualizar3.setGeometry(QtCore.QRect(390, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_actualizar3.setFont(font)
        self.boton_actualizar3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00aaff;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_actualizar3.setObjectName("boton_actualizar3")
        self.boton_eliminar3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_eliminar3.setGeometry(QtCore.QRect(720, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_eliminar3.setFont(font)
        self.boton_eliminar3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_eliminar3.setObjectName("boton_eliminar3")
        self.introducir_nom3 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_nom3.setGeometry(QtCore.QRect(60, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_nom3.setFont(font)
        self.introducir_nom3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_nom3.setObjectName("introducir_nom3")
        self.titulo_intro_datos3 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_intro_datos3.setGeometry(QtCore.QRect(0, 430, 1081, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_intro_datos3.sizePolicy().hasHeightForWidth())
        self.titulo_intro_datos3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.titulo_intro_datos3.setFont(font)
        self.titulo_intro_datos3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;")
        self.titulo_intro_datos3.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_intro_datos3.setObjectName("titulo_intro_datos3")
        self.introducir_email = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_email.setGeometry(QtCore.QRect(390, 570, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_email.setFont(font)
        self.introducir_email.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_email.setObjectName("introducir_email")
        self.boton_agregar3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_agregar3.setGeometry(QtCore.QRect(60, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_agregar3.setFont(font)
        self.boton_agregar3.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00ff00;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_agregar3.setObjectName("boton_agregar3")
        self.introducir_espe = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_espe.setGeometry(QtCore.QRect(720, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_espe.setFont(font)
        self.introducir_espe.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_espe.setObjectName("introducir_espe")
        crud_medi.setCentralWidget(self.centralwidget)

        self.retranslateUi(crud_medi)
        QtCore.QMetaObject.connectSlotsByName(crud_medi)

    def retranslateUi(self, crud_medi):
        _translate = QtCore.QCoreApplication.translate
        crud_medi.setWindowTitle(_translate("crud_medi", "MainWindow"))
        self.titulo_crud_medi.setText(_translate("crud_medi", "Datos de médico"))
        self.introducir_tel3.setPlaceholderText(_translate("crud_medi", "teléfono"))
        self.introducir_ap3.setPlaceholderText(_translate("crud_medi", "apellido"))
        self.boton_salir6.setText(_translate("crud_medi", "Salir"))
        self.boton_actualizar3.setText(_translate("crud_medi", "Actualizar"))
        self.boton_eliminar3.setText(_translate("crud_medi", "Eliminar"))
        self.introducir_nom3.setPlaceholderText(_translate("crud_medi", "nombre"))
        self.titulo_intro_datos3.setText(_translate("crud_medi", "Introducir datos"))
        self.introducir_email.setPlaceholderText(_translate("crud_medi", "email"))
        self.boton_agregar3.setText(_translate("crud_medi", "Agregar"))
        self.introducir_espe.setPlaceholderText(_translate("crud_medi", "especialidad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crud_medi = QtWidgets.QMainWindow()
    ui = Ui_crud_medi()
    ui.setupUi(crud_medi)
    crud_medi.show()
    sys.exit(app.exec_())
