# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Usuarios import leer_usuarios, actualizar_usuario, crear_usuario


class Ui_crud_user(object):
    def setupUi(self, crud_user):
        crud_user.setObjectName("crud_user")
        crud_user.resize(1080, 700)
        crud_user.setMinimumSize(QtCore.QSize(1080, 700))
        crud_user.setMaximumSize(QtCore.QSize(1080, 700))
        self.centralwidget = QtWidgets.QWidget(crud_user)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_agregar.setGeometry(QtCore.QRect(60, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_agregar.setFont(font)
        self.boton_agregar.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00ff00;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_agregar.setObjectName("boton_agregar")
        self.boton_salir4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir4.setGeometry(QtCore.QRect(920, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(30)
        self.boton_salir4.setFont(font)
        self.boton_salir4.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 30pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_salir4.setObjectName("boton_salir4")
        self.titulo_crud_users = QtWidgets.QLabel(self.centralwidget)
        self.titulo_crud_users.setGeometry(QtCore.QRect(0, 50, 1081, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG Inline")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_crud_users.setFont(font)
        self.titulo_crud_users.setStyleSheet("font-family: Decotura ICG Inline;\n"
"font-size: 50pt;")
        self.titulo_crud_users.setTextFormat(QtCore.Qt.PlainText)
        self.titulo_crud_users.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_crud_users.setObjectName("titulo_crud_users")
        self.boton_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_eliminar.setGeometry(QtCore.QRect(720, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_eliminar.setFont(font)
        self.boton_eliminar.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.boton_actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_actualizar.setGeometry(QtCore.QRect(390, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_actualizar.setFont(font)
        self.boton_actualizar.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00aaff;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.tabla_users = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_users.setGeometry(QtCore.QRect(50, 140, 981, 192))
        self.tabla_users.setObjectName("tabla_users")
        leer_usuarios(self.tabla_users)
        self.titulo_intro_datos = QtWidgets.QLabel(self.centralwidget)
        self.titulo_intro_datos.setGeometry(QtCore.QRect(0, 430, 1081, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_intro_datos.sizePolicy().hasHeightForWidth())
        self.titulo_intro_datos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.titulo_intro_datos.setFont(font)
        self.titulo_intro_datos.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;")
        self.titulo_intro_datos.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_intro_datos.setObjectName("titulo_intro_datos")
        self.introducir_ap = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_ap.setGeometry(QtCore.QRect(390, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_ap.setFont(font)
        self.introducir_ap.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_ap.setObjectName("introducir_ap")
        self.introducir_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_nom.setGeometry(QtCore.QRect(60, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_nom.setFont(font)
        self.introducir_nom.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_nom.setObjectName("introducir_nom")
        self.introducir_contra = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_contra.setGeometry(QtCore.QRect(60, 570, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_contra.setFont(font)
        self.introducir_contra.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_contra.setObjectName("introducir_contra")
        self.introducir_user = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_user.setGeometry(QtCore.QRect(720, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_user.setFont(font)
        self.introducir_user.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_user.setObjectName("introducir_user")
        self.introducir_tel = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_tel.setGeometry(QtCore.QRect(720, 570, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_tel.setFont(font)
        self.introducir_tel.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_tel.setObjectName("introducir_tel")
        self.introducir_rol = QtWidgets.QComboBox(self.centralwidget)
        self.introducir_rol.setGeometry(QtCore.QRect(390, 570, 301, 51))
        self.introducir_rol.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_rol.setObjectName("introducir_rol")
        self.introducir_rol.addItem("")
        self.introducir_rol.addItem("")
        self.introducir_rol.addItem("")
        self.titulo_intro_datos.raise_()
        self.titulo_crud_users.raise_()
        self.boton_agregar.raise_()
        self.boton_salir4.raise_()
        self.boton_eliminar.raise_()
        self.boton_actualizar.raise_()
        self.tabla_users.raise_()
        self.introducir_ap.raise_()
        self.introducir_nom.raise_()
        self.introducir_contra.raise_()
        self.introducir_user.raise_()
        self.introducir_tel.raise_()
        self.introducir_rol.raise_()
        crud_user.setCentralWidget(self.centralwidget)

        self.retranslateUi(crud_user)
        QtCore.QMetaObject.connectSlotsByName(crud_user)
        
        self.boton_actualizar.clicked.connect(self.actualizar_usuario)
        self.boton_agregar.clicked.connect(self.agregar_usuario)
        self.tabla_users.selectionModel().selectionChanged.connect(self.actualizar_campos)
        
    def actualizar_usuario(self):
        fila_seleccionada = self.tabla_users.currentRow()
        if fila_seleccionada == -1:
            QtWidgets.QMessageBox.warning(None, "Advertencia", "Selecciona un usuario para actualizar.")
            return
        
        # Obtén el ID del usuario de la primera columna (o ajusta según la estructura)
        user_id = self.tabla_users.item(fila_seleccionada, 0).text()
        
        # Obtén los nuevos valores de los campos de entrada
        nombre = self.introducir_nom.text()
        apellido = self.introducir_ap.text()
        usuario = self.introducir_user.text()
        telefono = self.introducir_tel.text()
        contraseña = self.introducir_contra.text()
        rol = self.introducir_rol.currentText()
        
        if not all([nombre, apellido, usuario, telefono, contraseña]):
            QtWidgets.QMessageBox.warning(None, "Advertencia", "Completa todos los campos para actualizar.")
            return
        if actualizar_usuario(user_id,nombre,apellido,usuario,contraseña,rol,telefono):
            QtWidgets.QMessageBox.information(None, "Éxito", "Usuario actualizado correctamente.")
            leer_usuarios(self.tabla_users) 
        else:
            QtWidgets.QMessageBox.critical(None, "Error", f"Error al actualizar: {err}")
        
    def agregar_usuario(self):
        fila_seleccionada = self.tabla_users.currentRow()
        if fila_seleccionada == -1:
            QtWidgets.QMessageBox.warning(None, "Advertencia", "Selecciona un usuario para actualizar.")
            return
        
        # Obtén los nuevos valores de los campos de entrada
        nombre = self.introducir_nom.text()
        apellido = self.introducir_ap.text()
        usuario = self.introducir_user.text()
        telefono = self.introducir_tel.text()
        contraseña = self.introducir_contra.text()
        rol = self.introducir_rol.currentText()
        
        if not all([nombre, apellido, usuario, telefono, contraseña]):
            QtWidgets.QMessageBox.warning(None, "Advertencia", "Completa todos los campos para actualizar.")
            return
        if crear_usuario(nombre,apellido,usuario,contraseña,rol,telefono):
            QtWidgets.QMessageBox.information(None, "Éxito", "Usuario creado correctamente.")
            leer_usuarios(self.tabla_users) 
        else:
            QtWidgets.QMessageBox.critical(None, "Error", f"Error al crear: {err}")

    def actualizar_campos(self):
        fila_seleccionada = self.tabla_users.currentRow()
        if fila_seleccionada == -1:
                return

        nombre = self.tabla_users.item(fila_seleccionada, 1).text()  
        apellido = self.tabla_users.item(fila_seleccionada, 2).text()  
        usuario = self.tabla_users.item(fila_seleccionada, 3).text()  
        contraseña = self.tabla_users.item(fila_seleccionada, 4).text()  
        rol = self.tabla_users.item(fila_seleccionada, 5).text()  
        telefono = self.tabla_users.item(fila_seleccionada, 6).text()  

        self.introducir_nom.setText(nombre)
        self.introducir_ap.setText(apellido)
        self.introducir_user.setText(usuario)
        self.introducir_tel.setText(telefono)
        self.introducir_contra.setText(contraseña)

        # Selecciona el rol correspondiente
        index_rol = self.introducir_rol.findText(rol)
        if index_rol != -1:
                self.introducir_rol.setCurrentIndex(index_rol)

    def retranslateUi(self, crud_user):
        _translate = QtCore.QCoreApplication.translate
        crud_user.setWindowTitle(_translate("crud_user", "MainWindow"))
        self.boton_agregar.setText(_translate("crud_user", "Agregar"))
        self.boton_salir4.setText(_translate("crud_user", "Salir"))
        self.titulo_crud_users.setText(_translate("crud_user", "Datos de usuario"))
        self.boton_eliminar.setText(_translate("crud_user", "Eliminar"))
        self.boton_actualizar.setText(_translate("crud_user", "Actualizar"))
        self.titulo_intro_datos.setText(_translate("crud_user", "Introducir datos"))
        self.introducir_ap.setPlaceholderText(_translate("crud_user", "apellido"))
        self.introducir_nom.setPlaceholderText(_translate("crud_user", "nombre"))
        self.introducir_contra.setPlaceholderText(_translate("crud_user", "contraseña"))
        self.introducir_user.setPlaceholderText(_translate("crud_user", "usuario"))
        self.introducir_tel.setPlaceholderText(_translate("crud_user", "teléfono"))
        self.introducir_rol.setItemText(0, _translate("crud_user", "superusuario"))
        self.introducir_rol.setItemText(1, _translate("crud_user", "administrador"))
        self.introducir_rol.setItemText(2, _translate("crud_user", "recepcionista"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crud_user = QtWidgets.QMainWindow()
    ui = Ui_crud_user()
    ui.setupUi(crud_user)
    crud_user.show()
    sys.exit(app.exec_())
