# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud_est.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crud_est(object):
    def setupUi(self, crud_est):
        crud_est.setObjectName("crud_est")
        crud_est.resize(1080, 700)
        crud_est.setMinimumSize(QtCore.QSize(1080, 700))
        crud_est.setMaximumSize(QtCore.QSize(1080, 700))
        self.centralwidget = QtWidgets.QWidget(crud_est)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo_crud_est = QtWidgets.QLabel(self.centralwidget)
        self.titulo_crud_est.setGeometry(QtCore.QRect(0, 50, 1081, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG Inline")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_crud_est.setFont(font)
        self.titulo_crud_est.setStyleSheet("font-family: Decotura ICG Inline;\n"
"font-size: 50pt;")
        self.titulo_crud_est.setTextFormat(QtCore.Qt.PlainText)
        self.titulo_crud_est.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_crud_est.setObjectName("titulo_crud_est")
        self.tabla_est = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_est.setGeometry(QtCore.QRect(50, 140, 981, 192))
        self.tabla_est.setObjectName("tabla_est")
        self.tabla_est.setColumnCount(0)
        self.tabla_est.setRowCount(0)
        self.boton_salir8 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir8.setGeometry(QtCore.QRect(920, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(30)
        self.boton_salir8.setFont(font)
        self.boton_salir8.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 30pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_salir8.setObjectName("boton_salir8")
        self.boton_actualizar5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_actualizar5.setGeometry(QtCore.QRect(390, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_actualizar5.setFont(font)
        self.boton_actualizar5.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00aaff;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_actualizar5.setObjectName("boton_actualizar5")
        self.boton_eliminar5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_eliminar5.setGeometry(QtCore.QRect(720, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_eliminar5.setFont(font)
        self.boton_eliminar5.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_eliminar5.setObjectName("boton_eliminar5")
        self.introducir_nom5 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_nom5.setGeometry(QtCore.QRect(60, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_nom5.setFont(font)
        self.introducir_nom5.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_nom5.setObjectName("introducir_nom5")
        self.titulo_intro_datos = QtWidgets.QLabel(self.centralwidget)
        self.titulo_intro_datos.setGeometry(QtCore.QRect(0, 430, 1081, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_intro_datos.sizePolicy().hasHeightForWidth())
        self.titulo_intro_datos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.titulo_intro_datos.setFont(font)
        self.titulo_intro_datos.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;")
        self.titulo_intro_datos.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_intro_datos.setObjectName("titulo_intro_datos")
        self.boton_agregar5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_agregar5.setGeometry(QtCore.QRect(60, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_agregar5.setFont(font)
        self.boton_agregar5.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00ff00;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_agregar5.setObjectName("boton_agregar5")
        self.introducir_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_precio.setGeometry(QtCore.QRect(720, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_precio.setFont(font)
        self.introducir_precio.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_precio.setObjectName("introducir_precio")
        self.introducir_tipo = QtWidgets.QComboBox(self.centralwidget)
        self.introducir_tipo.setGeometry(QtCore.QRect(390, 490, 301, 51))
        self.introducir_tipo.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_tipo.setObjectName("introducir_tipo")
        self.introducir_tipo.addItem("")
        self.introducir_tipo.addItem("")
        crud_est.setCentralWidget(self.centralwidget)

        self.retranslateUi(crud_est)
        QtCore.QMetaObject.connectSlotsByName(crud_est)

    def retranslateUi(self, crud_est):
        _translate = QtCore.QCoreApplication.translate
        crud_est.setWindowTitle(_translate("crud_est", "MainWindow"))
        self.titulo_crud_est.setText(_translate("crud_est", "Datos de estudio"))
        self.boton_salir8.setText(_translate("crud_est", "Salir"))
        self.boton_actualizar5.setText(_translate("crud_est", "Actualizar"))
        self.boton_eliminar5.setText(_translate("crud_est", "Eliminar"))
        self.introducir_nom5.setPlaceholderText(_translate("crud_est", "nombre"))
        self.titulo_intro_datos.setText(_translate("crud_est", "Introducir datos"))
        self.boton_agregar5.setText(_translate("crud_est", "Agregar"))
        self.introducir_precio.setPlaceholderText(_translate("crud_est", "precio"))
        self.introducir_tipo.setItemText(0, _translate("crud_est", "clínico"))
        self.introducir_tipo.setItemText(1, _translate("crud_est", "especializado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crud_est = QtWidgets.QMainWindow()
    ui = Ui_crud_est()
    ui.setupUi(crud_est)
    crud_est.show()
    sys.exit(app.exec_())
