# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud_paci.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crud_paci(object):
    def setupUi(self, crud_paci):
        crud_paci.setObjectName("crud_paci")
        crud_paci.resize(1080, 700)
        crud_paci.setMinimumSize(QtCore.QSize(1080, 700))
        crud_paci.setMaximumSize(QtCore.QSize(1080, 700))
        self.centralwidget = QtWidgets.QWidget(crud_paci)
        self.centralwidget.setObjectName("centralwidget")
        self.introducir_ap2 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_ap2.setGeometry(QtCore.QRect(390, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_ap2.setFont(font)
        self.introducir_ap2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_ap2.setObjectName("introducir_ap2")
        self.titulo_intro_datos2 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_intro_datos2.setGeometry(QtCore.QRect(0, 430, 1081, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_intro_datos2.sizePolicy().hasHeightForWidth())
        self.titulo_intro_datos2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.titulo_intro_datos2.setFont(font)
        self.titulo_intro_datos2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;")
        self.titulo_intro_datos2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_intro_datos2.setObjectName("titulo_intro_datos2")
        self.boton_eliminar2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_eliminar2.setGeometry(QtCore.QRect(720, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_eliminar2.setFont(font)
        self.boton_eliminar2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_eliminar2.setObjectName("boton_eliminar2")
        self.introducir_nom2 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_nom2.setGeometry(QtCore.QRect(60, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_nom2.setFont(font)
        self.introducir_nom2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_nom2.setObjectName("introducir_nom2")
        self.boton_actualizar2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_actualizar2.setGeometry(QtCore.QRect(390, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_actualizar2.setFont(font)
        self.boton_actualizar2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00aaff;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_actualizar2.setObjectName("boton_actualizar2")
        self.titulo_crud_paci = QtWidgets.QLabel(self.centralwidget)
        self.titulo_crud_paci.setGeometry(QtCore.QRect(0, 50, 1081, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG Inline")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titulo_crud_paci.setFont(font)
        self.titulo_crud_paci.setStyleSheet("font-family: Decotura ICG Inline;\n"
"font-size: 50pt;")
        self.titulo_crud_paci.setTextFormat(QtCore.Qt.PlainText)
        self.titulo_crud_paci.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_crud_paci.setObjectName("titulo_crud_paci")
        self.tabla_paci = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_paci.setGeometry(QtCore.QRect(50, 140, 981, 192))
        self.tabla_paci.setObjectName("tabla_paci")
        self.tabla_paci.setColumnCount(0)
        self.tabla_paci.setRowCount(0)
        self.boton_agregar2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_agregar2.setGeometry(QtCore.QRect(60, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.boton_agregar2.setFont(font)
        self.boton_agregar2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"background-color: #00ff00;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_agregar2.setObjectName("boton_agregar2")
        self.boton_salir5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_salir5.setGeometry(QtCore.QRect(920, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(30)
        self.boton_salir5.setFont(font)
        self.boton_salir5.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 30pt;\n"
"background-color: #ff0000;\n"
"border-radius: 20px;\n"
"color: white;")
        self.boton_salir5.setObjectName("boton_salir5")
        self.introducir_tel2 = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_tel2.setGeometry(QtCore.QRect(390, 570, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_tel2.setFont(font)
        self.introducir_tel2.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_tel2.setObjectName("introducir_tel2")
        self.introducir_fecha = QtWidgets.QLineEdit(self.centralwidget)
        self.introducir_fecha.setGeometry(QtCore.QRect(720, 490, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Decotura ICG")
        font.setPointSize(20)
        self.introducir_fecha.setFont(font)
        self.introducir_fecha.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border-radius: 20px;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_fecha.setObjectName("introducir_fecha")
        self.introducir_sexo = QtWidgets.QComboBox(self.centralwidget)
        self.introducir_sexo.setGeometry(QtCore.QRect(60, 570, 301, 51))
        self.introducir_sexo.setStyleSheet("font-family: Decotura ICG;\n"
"font-size: 20pt;\n"
"border: 3px solid #c0c0c0;\n"
"padding: 5px;")
        self.introducir_sexo.setObjectName("introducir_sexo")
        self.introducir_sexo.addItem("")
        self.introducir_sexo.addItem("")
        crud_paci.setCentralWidget(self.centralwidget)

        self.retranslateUi(crud_paci)
        QtCore.QMetaObject.connectSlotsByName(crud_paci)

    def retranslateUi(self, crud_paci):
        _translate = QtCore.QCoreApplication.translate
        crud_paci.setWindowTitle(_translate("crud_paci", "MainWindow"))
        self.introducir_ap2.setPlaceholderText(_translate("crud_paci", "apellido"))
        self.titulo_intro_datos2.setText(_translate("crud_paci", "Introducir datos"))
        self.boton_eliminar2.setText(_translate("crud_paci", "Eliminar"))
        self.introducir_nom2.setPlaceholderText(_translate("crud_paci", "nombre"))
        self.boton_actualizar2.setText(_translate("crud_paci", "Actualizar"))
        self.titulo_crud_paci.setText(_translate("crud_paci", "Datos de paciente"))
        self.boton_agregar2.setText(_translate("crud_paci", "Agregar"))
        self.boton_salir5.setText(_translate("crud_paci", "Salir"))
        self.introducir_tel2.setPlaceholderText(_translate("crud_paci", "teléfono"))
        self.introducir_fecha.setPlaceholderText(_translate("crud_paci", "fecha de nacimiento"))
        self.introducir_sexo.setItemText(0, _translate("crud_paci", "masculino"))
        self.introducir_sexo.setItemText(1, _translate("crud_paci", "femenino"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crud_paci = QtWidgets.QMainWindow()
    ui = Ui_crud_paci()
    ui.setupUi(crud_paci)
    crud_paci.show()
    sys.exit(app.exec_())
